### ISSUE TITLE
backups里的Android Notification的使用中通知无法显示问题

### ISSUE THREAD

**Issue by wjc3594** [leavesC/JavaLearn#2]

**Comment by callzhangmin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wjc3594** [comment]
需要加上这行代码：
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {               
     notificationManager.createNotificationChannel(NotificationChannel("0","name",NotificationManager.IMPORTANCE_HIGH))
 }
NotificationChannel的第一个参数“0”是我自己定义的，只需和NotificationCompat.Builder(requireActivity(), "0")的第二个参数保持一致即可

**Comment by leavesCZY** [comment]
@wjc3594 那应该是当时还没有 channel 这个概念？？感谢勘误。backups 文件夹里的文章是我很久以前写的了，多多少少会有点问题

**Comment by callzhangmin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by edwinmarrodriguez852-coder** [comment]
Ufff

**Comment by callzhangmin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
